### ISSUE TITLE
Openvas Upgrade Availability

### ISSUE THREAD

**Issue by wlgrayjr** [Atomicorp/gvm#23] opened 2020-07-17 01:42 UTC
When will the latest version be available?  

Installed GVM Libraries (gvm-libs) version:        10.0.0
Latest available GVM Libraries (gvm-libs) version: 10.0.1

**Comment by cfi-gb** [comment] 2020-07-18 09:53
This is a duplicate of #21 and #18

**Comment by atomicturtle** [comment] 2020-08-09 19:13
Merging into #18

**Closed as completed by atomicturtle** 2020-08-09 19:13 UTC
